export const appActionType = {
  INIT: "INIT",
  SET_CELL: "SET_CELL",
  NEXT_STEP: "NEXT_STEP",
  PREV_STEP: "PREV_STEP",
  TOGGLE_AUTOSIMULATION: "TOGGLE_AUTOSIMULATION",
  ADD_ROW: "ADD_ROW",
  REMOVE_ROW: "REMOVE_ROW",
  ADD_COLUMN: "ADD_COLUMN",
  REMOVE_COLUMN: "REMOVE_COLUMN",
};
